on:
  workflow_dispatch:
jobs:
  customize-image:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setup-tools
      run: |
        sudo apt-get update
        sudo apt-get install libguestfs-tools -y
